'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4927
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace asp_var3_2012

    Partial Public Class Question5

        '''<summary>
        '''Contrôle Repeater1.
        '''</summary>
        '''<remarks>
        '''Champ généré automatiquement.
        '''Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
        '''</remarks>
        Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Contrôle Repeater2.
        '''</summary>
        '''<remarks>
        '''Champ généré automatiquement.
        '''Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
        '''</remarks>
        Protected WithEvents Repeater2 As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''Contrôle Button1.
        '''</summary>
        '''<remarks>
        '''Champ généré automatiquement.
        '''Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
        '''</remarks>
        Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Contrôle GridView1.
        '''</summary>
        '''<remarks>
        '''Champ généré automatiquement.
        '''Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
        '''</remarks>
        Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''Contrôle Button2.
        '''</summary>
        '''<remarks>
        '''Champ généré automatiquement.
        '''Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
        '''</remarks>
        Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
