create database EFM_Rej
use EFM_Rej
CREATE TABLE PROPEIETAIRE(
    NUM_PROP INT PRIMARY KEY,
    NOM_PROP VARCHAR(30),
    PRENOM_PROP VARCHAR(30),
    LOGINN VARCHAR(30),
    PASSWORDD VARCHAR(30)
)
CREATE TABLE BIENIMMOBILIER(
    NUM_BIEN INT PRIMARY KEY,
    ADRESSE VARCHAR(30),
    SUOERFICIE VARCHAR(30),
    NUM_PROP INT FOREIGN KEY REFERENCES PROPEIETAIRE(NUM_PROP),
    PRIX FLOAT
)
CREATE TABLE CONTRAT(
    NUM_CONTRAT INT PRIMARY KEY,
    DATE_CONTRAT DATE,
    NUM_BIEN INT FOREIGN KEY REFERENCES BIENIMMOBILIER(NUM_BIEN),
    DUREE INT
)

INSERT INTO PROPEIETAIRE VALUES(1,'NOM_PROP1','PRENOM_PROP1','LOGINN1','PASSWORDD1')
INSERT INTO PROPEIETAIRE VALUES(2,'NOM_PROP2','PRENOM_PROP2','LOGINN2','PASSWORDD2')
INSERT INTO PROPEIETAIRE VALUES(3,'NOM_PROP3','PRENOM_PROP3','LOGINN3','PASSWORDD3')

INSERT INTO BIENIMMOBILIER VALUES(1,'ADRESSE1','SUOERFICIE1',1,120.00)
INSERT INTO BIENIMMOBILIER VALUES(2,'ADRESSE2','SUOERFICIE2',2,140.00)
INSERT INTO BIENIMMOBILIER VALUES(3,'ADRESSE3','SUOERFICIE3',3,160.00)

INSERT INTO CONTRAT VALUES(1,'2020-10-10',1,10)
INSERT INTO CONTRAT VALUES(2,'2020-11-10',2,20)
INSERT INTO CONTRAT VALUES(3,'2020-12-10',3,30)

SELECT*FROM PROPEIETAIRE
SELECT*FROM BIENIMMOBILIER
SELECT*FROM CONTRAT



SELECT*FROM PROPEIETAIRE where NUM_PROP=


delete from CONTRAT where NUM_CONTRAT =

SELECT C.* FROM CONTRAT C ,BIENIMMOBILIER B where C.NUM_BIEN=B.NUM_BIEN and B.NUM_PROP=1


Update CONTRAT set DATE_CONTRAT='',NUM_BIEN=,DUREE= where NUM_CONTRAT=